### PR TITLE
Added 'newdata' argument to viterbi.msm (issue #18)

### PR DESCRIPTION
**Pull request by wjchulme**
Resolves issue #18. The new argument is called 'newdata' to match base `predict` generic methods, but not precious about this so feel free to modify this or anything else to suit the package style. It uses `modify_call` from the `pryr` package.

### CODE REVIEW

**Comment by chjackson** [comment]
Thanks for the patches.  It might be a week or two before I get around to testing them properly.  But just wondering what the difference is between `pryr::modify_call(x$call, list(fixedpars = TRUE))` and `x$call$fixedpars <- TRUE`?   

Likewise for the purrr functions used in your other patch, are there concise base R equivalents? 

I do like tidyverse stuff - it's a fault of mine that haven't got around to learning it all, but I'd rather not add dependencies unless necessary, and I'd prefer to keep a consistent code style within the package.

**Comment by wjchulme** [comment]
No rush to get these tested - I have them working for my purposes and it's up to you whether to test/edit/adopt them fully.

I understand the reluctance to add dependencies. Happy for this to be changed to `x$call$fixedpars <- TRUE` - I wasn't aware this was so simple in base R! I'll push a commit now that puts that in.

The `purrr` dependencies in pull #20 are not as easy to remove (I'll elaborate in the thread)

**Comment by wjchulme** [comment]
I've made a mess of the commit history to remove `purrr` dependency because I've no idea what I'm doing, but the latest commit is good to go

**Comment by helmingstay** [comment]
Bump - are this and #18 completed and/or merged?

**Comment by chjackson** [comment]
This has been belatedly merged and cleaned up in the latest commit - thanks.

**Pull request merged**
